### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by ankitjain28may** [ankitjain28may/openchat#26]
I want to make it easier to deploy this project on other platform more easily so I am thinking to integrate docker in the project.

**Comment by manishrw** [comment]
Can I take this up?

**Comment by ankitjain28may** [comment]
@manishrw Awesome, go at it.

**Comment by frost-queen** [comment]
is this issue still open? i would like to take this up.

**Comment by ankitjain28may** [comment]
Great

**Comment by kmjayadeep** [comment]
Can I take this up? I see that the issue is not closed yet

**Comment by ankitjain28may** [comment]
@kmjayadeep Sure, you can take this up

**Comment by ezerw** [comment]
I think this issue is already done right? @ankitjain28may

**Comment by ankitjain28may** [comment]
@ezerw Yupp, Thanks to you for the contribution.
