### ISSUE TITLE
Login form add username functionality

### ISSUE THREAD

**Issue by hiteshpr** [ankitjain28may/openchat#54]
On homepage in the Login form, We can use a username or email ID but if a username is entered which is not in email format the app shows error. We need to change the functionality of checking for email/username.

**Comment by ankitjain28may** [comment]
@hiteshpr Let me check once, i think i have already implemented this functionality

**Comment by hiteshpr** [comment]
@ankitjain28may is the functionality present?

**Comment by ankitjain28may** [comment]
@hiteshpr Yes this functionality is present, i checked and its working fine.
